name: Release
on:
  release:
    types:
      - published
permissions:
  actions: read
  contents: read
  id-token: write
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache installs
        uses: ./.github/actions/cache-install
        with:
          os-name: ${{ runner.os }}

  deploy_firestore:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-install
        with:
          os-name: ${{ runner.os }}
      - name: Authenticate Firebase
        uses: google-github-actions/auth@v2.1.8
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy firestore
        run: npx firebase deploy --only=firestore --project ${{ secrets.FIREBASE_PROJECT_NAME }}

  deploy_firebase_hosting:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-install
        with:
          os-name: ${{ runner.os }}
      - name: Derive appropriate SHAs
        uses: nrwl/nx-set-shas@v4
      - name: Create .env file
        run: |
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > ./packages/frontend/.env.build.production
      - name: Lint and build
        run: npx nx build frontend  --configuration production
      - name: Authenticate Firebase
        uses: google-github-actions/auth@v2.1.8
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy firebase hosting
        run: npx firebase deploy --only=hosting --project ${{ secrets.FIREBASE_PROJECT_NAME }}
      - name: Clean up
        run: |
          rm ./packages/frontend/.env.build.production

  deploy_firebase_functions:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-install
        with:
          os-name: ${{ runner.os }}
      - name: Lint and build
        run: npx nx build functions
      - name: Authenticate Firebase
        uses: google-github-actions/auth@v2.1.8
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy firebase functions
        run: npx firebase deploy --only=functions --project ${{ secrets.FIREBASE_PROJECT_NAME }}